#!/bin/sh
Debloat() {

  # CHECK IF IT CAN BE REACHED BY ABD
  clear
  if adb get-state 1>/dev/null 2>&1; then

    # NOTIFY CHANGES
    clear
    printf "[2] Disabling the following packages:\n\n"

    # DISABLE PACKAGES
    packages=(
        com.amazon.recess
        com.amazon.ssmsys
        com.amazon.whisperplay.contracts
        com.ivona.orchestrator
        com.amazon.dpcclient
        com.amazon.ceviche
        com.amazon.alta.h2clientservice
        com.amazon.ftv.screensaver
        com.amazon.ods.kindleconnect
        com.android.providers.downloads.ui
        com.amazon.sharingservice.android.client.proxy
        com.amazon.android.marketplace
        com.amazon.tifobserver
        com.amazon.aca
        com.amazon.ale
        com.amazon.dcp
        com.amazon.ssm
        com.amazon.tahoe
        com.amazon.naatyam
        com.amazon.tv.fw.metrics
        com.amazon.device.sale.service
        com.amazon.cardinal
        com.amazon.tv.forcedotaupdater.v2
        amazon.jackson19
        com.android.managedprovisioning
        com.amazon.imdb.tv.android.app
        com.amazon.tmm.tutorial
        com.amazon.dcp.contracts.framework.library
        com.amazon.tv.support
        com.amazon.sync.provider.ipc
        com.amazon.tv.legal.notices
        android.amazon.perm
        com.amazon.kso.blackbird
        com.amazon.providers.contentsupport
        com.amazon.whisperjoin.middleware.np
        com.amazon.application.compatibility.enforcer
        com.amazon.whisperplay.service.install
        com.ivona.tts.oem
        com.amazon.shoptv.client
        com.amazon.communication.discovery
        com.amazon.tv.releasenotes
        com.amazon.hedwig
        com.amazon.application.compatibility.enforcer.sdk.library
        com.android.bluetoothmidiservice
        com.android.dreams.basic
        com.android.wallpaperbackup
        com.amazon.bueller.photos
        com.amazon.vizzini
        com.svox.pico
        com.amazon.bueller.music
        com.amazon.connectivitydiag
        com.amazon.awvflingreceiver
        com.amazon.logan
        com.android.documentsui
        com.amazon.tahoe
        com.amazon.hedwig
        com.amazon.wifilocker
        com.amazon.franktvinput
        com.amazon.alexa.externalmediaplayer.fireos
        com.amazon.tv.alexaalerts
        com.amazon.tv.alexanotifications
        com.amazon.katoch
    )
    
    # Loop through the array and disable each package
    for package in "${packages[@]}"
    do
        adb shell pm disable-user "$package"
    done

  else
    # IT FAILED, TELL REMEDY AND PROMPT RETRY
    printf "[Error] Fire TV is not reachable, please confirm:\n\n"
    printf "  - ADB debugging is enabled on the Fire TV\n"
    printf "  - This is the IP address of the Fire TV\n\n"
    read -p "Press any key to try again: " -n 1 -s key
    Main
  fi
}

Main() {
  # CHECK IF HOMEBREW IS INSTALLED, IF NOT ASK TO INSTALL IT
  which -s /opt/homebrew/bin/brew
  if [[ $? != 0 ]]; then
    clear
    printf "[Error] Homebrew is not installed, please continue with its installation and then rerun the script:\n\n"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    Main
  else
    # CHECK IF ANDROID PLATFORM TOOLS IS INSTALLED, IF NOT INSTALL IT
    if /opt/homebrew/bin/brew list | grep "android-platform-tools" >/dev/null 2>&1; then
      # CLEAR CURRENT CONNECTIONS
      adb disconnect
      clear

      # ASK FOR IP

      printf "╔═════════════════════════╗\n"
      printf "║     Debloat Fire TV     ║\n"
      printf "╚═════════════════════════╝\n\n"

      printf "[1] Enter your Fire TV's IP Address: "
      read ip1

      # CHECK IF HOST IS ONLINE, IF SO TRY AND CONNECT
      if
        ping -c 1 "$ip1" >/dev/null 2>&1
      then
        adb connect $ip1:5555
        Debloat
      else
        # IT FAILED, TELL REMEDY AND PROMPT RETRY
        clear
        printf "[Error] This IP address is not reachable, please confirm that:\n\n"
        printf "  - Both devices are on the same network\n"
        printf "  - The IP address is typed correctly\n\n"
        read -p "Press any key to try again: " -n 1 -s key
        Main
      fi
    else
      # INSTALL ANDROID PLATFORM TOOLS, AND RESTART THE SCRIPT
      /opt/homebrew/bin/brew install --cask android-platform-tools
      Main
    fi
  fi
}

Main
